name: Test, Build and Publish
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Get package version
      uses: tyankatsu0105/read-package-version-actions@v1
      id: package-version
    - run: npm install
    - run: npm test
    - run: npm run build
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
    - uses: actions/upload-artifact@v2
      with:
        name: Pikaso Bundles ${{ steps.package-version.outputs.current-version}}
        path: dist